### ISSUE TITLE
Support Copy-GCSObject from one bucket to another

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-powershell#126] opened 2016-07-14 21:41 UTC
Currently trying:
Find-GcsObject -Bucket ynrpizza | Read-GcsObject -Bucket ynrpizza | New-GcsObject -bucket usertestbucket

Might be good to support copy so that the data does not need to transit through my machine.

**Comment by ILMTitan** [comment] 2016-08-30 22:38
Duplicate of #91.

**Closed by ILMTitan** 2016-08-30 22:38 UTC
Labels: GCS
