### ISSUE TITLE
Can't redirect output to a file on gs:\

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-powershell#374] opened 2016-11-10 20:18 UTC
```
PS gs:\bookshelf-dotnet> cat .\your-file.txt
My text object content
PS gs:\bookshelf-dotnet> echo "`nI love PSProviders" >> your-file.txt
out-file : Cannot open file because the current provider (Google.PowerShell\GoogleCloudStorage) cannot open a file.
At line:1 char:1
+ echo "`nI love PSProviders" >> your-file.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Out-File], PSInvalidOperationException
    + FullyQualifiedErrorId : ReadWriteFileNotFileSystemProvider,Microsoft.PowerShell.Commands.OutFileCommand
PS gs:\bookshelf-dotnet> echo "`nI love PSProviders" >> ~your-file.txt
out-file : Cannot open file because the current provider (Google.PowerShell\GoogleCloudStorage) cannot open a file.
At line:1 char:1
+ echo "`nI love PSProviders" >> ~your-file.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Out-File], PSInvalidOperationException
    + FullyQualifiedErrorId : ReadWriteFileNotFileSystemProvider,Microsoft.PowerShell.Commands.OutFileCommand
PS gs:\bookshelf-dotnet> echo "`nI love PSProviders" >> ~\your-file.txt
out-file : Home location for this provider is not set. To set the home location, call "(get-psprovider
'GoogleCloudStorage').Home = 'path'".
At line:1 char:1
+ echo "`nI love PSProviders" >> ~\your-file.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Out-File], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.OutFileCommand

PS gs:\bookshelf-dotnet> echo "`nI love PSProviders" >> "c:\users\Jeffrey Rennie\Documents\your-file.txt"
PS gs:\bookshelf-dotnet> echo "`nI love PSProviders" >> another-file.txt
out-file : Cannot open file because the current provider (Google.PowerShell\GoogleCloudStorage) cannot open a file.
At line:1 char:1
+ echo "`nI love PSProviders" >> another-file.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Out-File], PSInvalidOperationException
    + FullyQualifiedErrorId : ReadWriteFileNotFileSystemProvider,Microsoft.PowerShell.Commands.OutFileCommand
PS gs:\bookshelf-dotnet> echo "`nI love PSProviders" >>another-file.txt
out-file : Cannot open file because the current provider (Google.PowerShell\GoogleCloudStorage) cannot open a file.
At line:1 char:1
+ echo "`nI love PSProviders" >>another-file.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Out-File], PSInvalidOperationException
    + FullyQualifiedErrorId : ReadWriteFileNotFileSystemProvider,Microsoft.PowerShell.Commands.OutFileCommand
PS gs:\bookshelf-dotnet> echo "`nI love PSProviders" > another-file.txt
out-file : Cannot open file because the current provider (Google.PowerShell\GoogleCloudStorage) cannot open a file.
At line:1 char:1
+ echo "`nI love PSProviders" > another-file.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Out-File], PSInvalidOperationException
    + FullyQualifiedErrorId : ReadWriteFileNotFileSystemProvider,Microsoft.PowerShell.Commands.OutFileCommand
PS gs:\bookshelf-dotnet>
```

**Comment by quoctruong** [comment] 2016-11-15 17:34
This is duplicate of https://github.com/GoogleCloudPlatform/google-cloud-powershell/issues/352.

**Closed by quoctruong** 2016-11-15 17:34 UTC
Labels: GCS-Provider
