### ISSUE TITLE
GCS should have a powershell drive provider.

### ISSUE THREAD

**Issue by EricSL** [GoogleCloudPlatform/google-cloud-powershell#311] opened 2016-09-09 00:16 UTC
https://msdn.microsoft.com/en-us/library/ee126186(v=vs.85).aspx

This would allow all the regular file management and many other powershell cmdlets that indirectly use them to work with GCS buckets. Ideally you could register a "gs:" drive and then commands like "Copy-Item C:\local_file.txt gs://my_bucket/folder/" would work.

**Comment by chrsmith** [comment] 2016-09-09 00:19
That's a great idea! Fortunately, we got you covered. In fact, the PowerShell provider for Google Cloud Storage was submitted _just this afternoon_ by @ILMTitan in commit 85ad1b31081e883e850313c3d769603f1ad49bb7.

We still need to do some testing, documentation, etc. But we should have that generally available in the next few weeks.

**Comment by ILMTitan** [comment] 2016-09-09 00:24
Hello EricSL. I am glad you are interested in our powershell cmdlets.
This issue is:
Duplicate of #11.
Closed in #282.

**Closed by ILMTitan** 2016-09-09 00:24 UTC
Labels: enhancement, GCS
